name: LegendaryGuildRemapped
version: 6.0.8
api-version: '1.12'
author: Gyzer, RickGao
folia-supported: true
main: com.gyzer.LegendaryGuild
depend:
  - Vault
  - PlaceholderAPI
  - ProtocolLib
softdepend:
  - PlayerPoints
  - AttributePlus
  - SX-Attribute
  - MythicLib
commands:
  guild:
#    aliases: [legendaryguildremapped]